apiVersion: v1
kind: Namespace
metadata:
  name: loadgen
  labels:
    name: loadgen
    app: gke-loadgen
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    app: gke-loadgen
